adding call for just examining token

diff --git a/.github/workflows/delete-opensearch-indices.yml b/.github/workflows/delete-opensearch-indices.yml
--- a/.github/workflows/delete-opensearch-indices.yml
+++ b/.github/workflows/delete-opensearch-indices.yml
@@ -680,6 +680,61 @@ jobs:
             exit 0
           fi  
 
+      - name: Test setup curl rebuild call 
+        run: |
+          set -euo pipefail
+          set -x
+          INSTANCE_ID="${{ steps.discover-instance.outputs.INSTANCE_ID }}"
+          TIER="${{ env.TIER }}"
+
+          echo "Triggering OpenSearch index rebuild..."
+
+          COMMAND_ID=$(aws ssm send-command \
+            --instance-ids "$INSTANCE_ID" \
+            --document-name "AWS-RunShellScript" \
+            --comment "Rebuild OpenSearch index on $TIER" \
+            --parameters "commands=[\"export TOKEN=$(curl -fsS -X PUT \\\"http://169.254.169.254/latest/api/token\\\" -H \\\"X-aws-ec2-metadata-token-ttl-seconds: 21600\\\"); echo $TOKEN;  \"]" \   
+            --query "Command.CommandId" \
+            --output text)
+
+          if [ -z "$COMMAND_ID" ] || [ "$COMMAND_ID" == "None" ]; then
+            echo "❌ Error: Failed to send SSM command"
+            exit 1
+          fi
+
+          echo "✅ Command sent. Command ID: $COMMAND_ID"
+          echo "Waiting for command to complete..."
+
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id "$INSTANCE_ID"
+
+          FINAL_STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "$INSTANCE_ID" \
+            --query 'Status' \
+            --output text)
+    
+          if [ "$FINAL_STATUS" != "Success" ]; then
+            echo "❌ Error: Rebuild failed with status: $FINAL_STATUS"
+            aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "$INSTANCE_ID" \
+              --query '[Status, StandardOutputContent, StandardErrorContent]' \
+              --output table
+            exit 1
+          else  
+            echo "✅ Success: Indics rebuilt verified successfully on instance $INSTANCE_ID for tier $TIER"  
+            aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "$INSTANCE_ID" \
+              --query '[Status, StandardOutputContent, StandardErrorContent]' \
+              --output table
+            exit 0
+          fi
+
+
+
 
       - name: Rebuild OpenSearch index
         run: |
